export const JOB_POSITIONS = [
    'Frontend Developer',
    'Backend Developer',
    'Full Stack Developer',
    'Mobile Developer',
    'Cloud Engineer',
    'Data Scientist',
    'Machine Learning Engineer',
    'Product Manager',
    'Product Designer',
    'QA Engineer',
    'Security Engineer',
    'Database Administrator',
    'Blockchain Developer',
    'Game Developer',
];

export const JOB_LABEL_TO_ROLE: Record<string, string> = {
    'Frontend Developer': 'ROLE_FE',
    'Backend Developer': 'ROLE_BE',
    'Full Stack Developer': 'ROLE_FULLSTACK',
    'Mobile Developer': 'ROLE_MOBILE',
    'Cloud Engineer': 'ROLE_CLOUD',
    'Data Scientist': 'ROLE_DATA',
    'Machine Learning Engineer': 'ROLE_ML',
    'Product Manager': 'ROLE_PM',
    'Product Designer': 'ROLE_DESIGN',
    'QA Engineer': 'ROLE_QA',
    'Security Engineer': 'ROLE_SECURITY',
    'Database Administrator': 'ROLE_DBA',
    'Blockchain Developer': 'ROLE_BLOCKCHAIN',
    'Game Developer': 'ROLE_GAME',
};

export const JOB_ROLE_TO_LABEL: Record<string, string> = {
    'ROLE_FE': 'Frontend Developer',
    'ROLE_BE': 'Backend Developer',
    'ROLE_FULLSTACK': 'Full Stack Developer',
    'ROLE_MOBILE': 'Mobile Developer',
    'ROLE_CLOUD': 'Cloud Engineer',
    'ROLE_DATA': 'Data Scientist',
    'ROLE_ML': 'Machine Learning Engineer',
    'ROLE_PM': 'Product Manager',
    'ROLE_DESIGN': 'Product Designer',
    'ROLE_QA': 'QA Engineer',
    'ROLE_SECURITY': 'Security Engineer',
    'ROLE_DBA': 'Database Administrator',
    'ROLE_BLOCKCHAIN': 'Blockchain Developer',
    'ROLE_GAME': 'Game Developer',
};
